### ISSUE TITLE
Fehlende .gitignore

### ISSUE THREAD

**Issue by dariakoz** [Erfurter-Bahner/FlipFlOS#2]
Guten Tag liebe Kollegen des **FlipFIOS-Team**,

ich weiß nicht, welches Git-Seminar Ihr besucht habt, jedoch sind in eurem Repository offensichtliche **Wissenslücken** erkennbar.
Hier nochmal eine Reminder-Frage, die ihr euch selber stellen solltet: *Wisst ihr, was eine .gitignore Datei ist?*

Im Namen der Gruppe 1 hoffe ich, dass so eine Unstimmigkeit nicht mehr vorkommt. Wir sehen uns sonst gezwungen, Folgemaßnahmen einzuleiten, welche zu internen Konsequenzen führen.

Weiterhin wünsche ich Ihnen einen guten Wochenstart und viel Spaß beim Programmieren!!

<img src="https://github.com/user-attachments/assets/d017aa8b-f8fd-469f-a275-162f3cb2e87f" alt="Bild1" width="120"/>

**Vinzenz Geisler**
Co-Founder ErfurterBahn | Gruppe 1
1045 La Avenida St, Mountain View, Vereinigte Staaten

**Comment by PhillipSteph** [comment]
Ich bitte Sie, ihren Standort zu überarbeiten. Mit Betrüger Ammis arbeite ich nicht.
